---
<a name='title'></a>
# **<font color="Navy"> Temas Selectos </font>**
## **<font color="RoyalBlue"> Tema 1.4 Programación científica en Python </font>**
### **<font color="DodgerBlue"> Notebook 1: Operaciones con arreglos </font>**
#### Escuela Nacional de Ciencias de la Tierra
#### Semestre 2024-II

---


Objetivos: aprender a realizar las siguientes operaciones en el lenguaje Python a través de las paqueterías `numpy` y `scipy`.

Las paqueterías son un agregado de clases y funciones que permiten al usuario operar con ciertos objetos utilizando código pre-existente. Por ejemplo, si queremos obtener la evaluación de la función $f(x)=sen(x)$, ya existe una función que nos permitirá hacer este análisis.

Específicamente, vamos a ver algunas bases de programación científica. Para empezar, necesitamos ver operaciones básicas entre objetos matemáticos, vectores, matrices, números, etc.

*   Creación y operaciones con arreglos
*   Funciones geométricas
*   Álgebra lineal
*   Sistemas de ecuaciones
*   Integración numérica

También veremos algunas bases de graficación utilizando la paquetería de Python `matplotlib`.

Antes de empezar, es importante recordar que para acceder a diferentes funciones o módulos provenientes de una paquetería en Python se utiliza el punto "." como si fuera un apellido. Por ejemplo, en la paquetería de matplotlib se puede acceder al módulo de pyplot, que es el que utilizaremos para graficar de la siguiente manera:

```
matplotlib.pyplot
```

Ahora podemos empezar el notebook importando estas dos librerías que utilizaremos para la primera sección de este tema:

In [2]:
import numpy as np

import matplotlib.pyplot as plt

### Tema 1.4.1 Creación y operaciones con arreglos

Ahora podemos empezar a trabajar con numpy. En la celda anterior lo importamos pero haciendo un cambio de nombre, paso de ser numpy a `np`, podría haber sido cualquier cosa pero le pusimos np por convención. Así mismo, pyplot se abrevia como plt.


---


¿Qué es un arreglo?

*a) Arreglo np.array:*
Un arreglo np.array en NumPy es una estructura de datos que representa una matriz unidimensional, bidimensional o multidimensional, dependiendo de la forma de los datos proporcionados. Este objeto se crea utilizando la función numpy.array() y ofrece una amplia variedad de operaciones y funciones para manipular datos de manera eficiente. Los elementos en el arreglo son del mismo tipo, lo que permite realizar operaciones vectorizadas. Además, los arreglos NumPy admiten broadcasting, lo que facilita las operaciones entre arreglos de diferentes formas.

*b) Arreglo N dimensiones np.ndarray:*
Un arreglo np.ndarray es similar a un arreglo np.array, pero con la capacidad de representar arreglos de N dimensiones. Este objeto es la estructura de datos fundamental en NumPy y se utiliza para almacenar elementos homogéneos, ya sea en una matriz unidimensional, bidimensional o con más dimensiones. Los arreglos np.ndarray proporcionan funciones y métodos especializados para operaciones algebraicas y estadísticas, así como para manipulación de datos. Al igual que los arreglos unidimensionales, los arreglos N-dimensionales en NumPy permiten realizar operaciones eficientes debido a su naturaleza vectorizada.

Vamos a hacer nuestro primer arreglo:

In [3]:
# Creamos un arreglo de 1 al 3
arreglo=np.array([1,2,3])
print(arreglo)
# funcion type nos dice el tipo de objeto con el que estamos trabajando
print(type(arreglo))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# seleccionando la posicion 1
arreglo[1]

2

In [5]:
arreglo2=np.array([0,1,2,3,5,8])
print(arreglo2)
print(arreglo2[2])

[0 1 2 3 5 8]
2


En Python, un atributo de un objeto es una característica o propiedad asociada a una instancia particular de una clase. Estos atributos almacenan información sobre el estado del objeto y pueden ser variables que contienen datos específicos para esa instancia. Los atributos se definen en la clase y se asignan valores específicos cuando se crea una instancia del objeto. Pueden ser accedidos y modificados directamente desde el objeto.

Por ejemplo, consideremos una clase Persona que tiene atributos como nombre y edad:

In [6]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre  # Atributo "nombre"
        self.edad = edad      # Atributo "edad"

# Crear una instancia de la clase Persona
persona1 = Persona("Juan", 30)

# Acceder a los atributos
print("Nombre:", persona1.nombre)
print("Edad:", persona1.edad)

# Modificar un atributo
persona1.edad = 31
print("Nueva Edad:", persona1.edad)

Nombre: Juan
Edad: 30
Nueva Edad: 31


En este ejemplo, la clase Persona tiene dos atributos: nombre y edad. Cuando creamos una instancia de la clase (*persona1*), le asignamos valores específicos a estos atributos. Luego, podemos acceder a ellos o modificarlos directamente desde la instancia del objeto. Los atributos son esenciales para modelar y representar datos en objetos en Python.

Ahora vamos a regresar a nuestro arreglo de numpy y veremos algunos de sus atributos. Por ejemplo, podemos saber el tamaño del arreglo a través del atributo **.shape**.


In [7]:
arreglo.shape

(3,)

Ahora podemos hacer un segundo arreglo pero en este caso de 2 dimensiones, una manera de visualizarlo quizás más común a lo que estamos acostumbrados es:

$A=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
  \end{bmatrix}
$

In [8]:
# creamos el arreglo
arreglo_2D=np.array([[1,2,3],[4,5,6]])
# imprimimos el arreglo
print('Arreglo 2D')
print(arreglo_2D)
# aqui imprimimos las formas del arreglo 1 y el 2
print(arreglo_2D.shape,arreglo.shape)

Arreglo 2D
[[1 2 3]
 [4 5 6]]
(2, 3) (3,)


También podemos ver el tamaño total de un arreglo a través del atributo **.size** que mide el número total de elementos dentro de nuestro arreglo

In [9]:
arreglo_2D.size

6

---
<a name='ej-1'></a>
#### **<font color="DodgerBlue">Ejercicio 1 - Tamaño de arreglo.</font>**

<font color="DarkBlue"> Genere un arreglo de numpy con 5 elementos aleatorios y compruebe que su tamaño es de 5 elementos.

---

```python
# Arreglo
arreglo_ej1 = ...
# print tamaño
print()
```

---

### Slicing

En Python, para "seleccionar" o realizar "*slicing*" en un arreglo de NumPy de N dimensiones, se utiliza la notación de corchetes. Es importante tener en cuenta que Python utiliza indexación basada en cero, lo que significa que el primer elemento de un arreglo tiene índice 0. El slicing se realiza especificando rangos de índices dentro de los corchetes. La sintaxis general es `[inicio:fin:paso]`, donde inicio es el índice del primer elemento incluido, fin es el índice del primer elemento excluido y paso es el número de elementos que se salta en cada paso.



In [10]:
# Crear un arreglo bidimensional (matriz)
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('Matriz')
print(matriz)

# Seleccionar la primera fila (índice 0)
primera_fila = matriz[0, :]

# Seleccionar la segunda columna (índice 1)
segunda_columna = matriz[:, 1]

# Seleccionar un subconjunto de la matriz
submatriz = matriz[1:3, 0:2]

print("Primera fila:", primera_fila)
print("Segunda columna:", segunda_columna)
print("Submatriz:")
print(submatriz)

Matriz
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Primera fila: [1 2 3]
Segunda columna: [2 5 8]
Submatriz:
[[4 5]
 [7 8]]


En este ejemplo, se utiliza el slicing para seleccionar la primera fila, la segunda columna y un subconjunto de la matriz bidimensional. El resultado ilustra cómo la notación de corchetes y la indexación basada en cero facilitan la manipulación eficiente de arreglos NumPy en Python.

Por ejemplo, si regresamos a nuestro arreglo 2D original, podemos seleccionar la segunda fila, tercer columna a través del índice [1,2].

In [11]:
print(arreglo_2D[1,2])


6



---
<a name='ej-1'></a>
#### **<font color="DodgerBlue">Ejercicio 2 - Arreglo 2D </font>**

<font color="DarkBlue"> 1. Genere un arreglo de numpy de 3 dimensiones de la forma (3,2).

<font color="DarkBlue"> 2. Luego obtenga a través de un slice, o una submatriz, el elemento que se encuentra en la segunda fila primer columna.

---


### Operaciones básicas con arreglos

NumPy proporciona una amplia variedad de operaciones básicas que simplifican y aceleran el procesamiento de arreglos. Una de las características más destacadas es la vectorización, que permite realizar operaciones de manera eficiente en arreglos completos sin la necesidad de bucles explícitos. El uso del operador `*` realiza multiplicación elemento a elemento, mientras que `+`, `-`, y `/` realizan las operaciones aritméticas correspondientes. Estas operaciones están diseñadas para manejar arreglos de diferentes formas y dimensiones, lo que facilita el trabajo con datos multidimensionales de manera concisa y eficiente.

Un arreglo también puede ser multiplicado por un escalar o cada elemento puede ser elevada a una cierta potencia utilizando `**`



In [22]:
# Crear dos arreglos
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [23]:
# Multiplicación elemento a elemento
multiplicacion_elemento_a_elemento = arr1 * arr2
print("Multiplicación Elemento a Elemento:")
print(multiplicacion_elemento_a_elemento)

# Suma de arreglos
suma_arreglos = arr1 + arr2
print("\nSuma de Arreglos:")
print(suma_arreglos)


Multiplicación Elemento a Elemento:
[[ 7 16 27]
 [40 55 72]]

Suma de Arreglos:
[[ 8 10 12]
 [14 16 18]]


In [13]:
# Resta de arreglos
resta_arreglos = arr2 - arr1
print("\nResta de Arreglos:")
print(resta_arreglos)

# División elemento a elemento
division_elemento_a_elemento = arr2 / arr1
print("\nDivisión Elemento a Elemento:")
print(division_elemento_a_elemento)


Resta de Arreglos:
[[6 6 6]
 [6 6 6]]

División Elemento a Elemento:
[[7.  4.  3. ]
 [2.5 2.2 2. ]]


La operación anterior mantiene la forma de los vectores. De hecho podríamos comprobarlo con una impresión las formas de cada objeto.

El producto  de un escalar $\lambda$ por un vector $x \in
\Bbb{R}^n$ se define como:

\begin{align} \lambda x  =
\left(
  \begin{matrix}
  \lambda  x_1      \\
  \lambda x_2 \\
  \vdots \\
   \lambda x_n
  \end{matrix}
  \right)
\end{align}


In [14]:
print(2*arreglo)
for lambda_int in [1,2,3,4]:
    print('lambda',lambda_int,lambda_int*arreglo)

[2 4 6]
lambda 1 [1 2 3]
lambda 2 [2 4 6]
lambda 3 [3 6 9]
lambda 4 [ 4  8 12]



---
<a name='ej-1'></a>
#### **<font color="DodgerBlue">Ejercicio 3 - Operaciones con arreglos </font>**

<font color="DarkBlue"> Genere dos vectores $\vec{x}$ y $\vec{y}$, uno con valores aleatorios del 1 al 10 y otro con valores del 1 al 20. Luego calcule el vector  $\vec{z}$ si $\vec{z}=2\vec{x}+\vec{y}$.

```python
# Arreglo
y = ...
x = ...
z = ...
# print tamaño
print()
```

---

Ahora bien, si tenemos vectores, matrices y demás, podríamos en principio operar con ellas. Las operaciones básicas con arreglos de NumPy, especialmente las operaciones *vector-matriz* y los *productos punto*, son fundamentales en el ámbito de la computación científica y el análisis de datos. NumPy aprovecha la vectorización para realizar estas operaciones de manera eficiente, permitiendo que las funciones se apliquen elemento a elemento sin la necesidad de bucles explícitos en el código.

## Operaciones vector-matriz. 

Sea $\textbf{A}$ una matriz de dimensiones $m \times n$ y $\vec{x}$ un vector de dimensión $n$, la multiplicación de $\textbf{A}$ por $\vec{x}$ se realiza multiplicando cada fila de $\textbf{A}$  por el vector $\vec{x}$ y sumando los resultados. El resultado es un nuevo vector $\vec{y}$ de dimensión $m$, y la operación se expresa como:

\begin{align}
y = \textbf{A}\vec{x}
\end{align}

Donde $y_i = \sum_{j=1}^{n} A_{ij} \cdot x_j$  para $i = 1, 2, ..., m$

Es importante destacar que la dimensión de la matriz $\textbf{A}$  debe ser compatible con la dimensión del vector $\vec{x}$. Es decir, el número de columnas de $\textbf{A}$ debe ser igual al número de elementos en $\vec{x}$.

Por ejemplo, dada una matriz $\textbf{A}$ y un vector $\vec{x}$:

$A=\begin{bmatrix}
2 & 7 & 4 \\
3 & 1 & 0
  \end{bmatrix}
$

$\vec{x}=\begin{pmatrix}
1  \\
2 \\
3
  \end{pmatrix}
$
 podemos calcular el resultado de la multiplicación

 \begin{align}
y = \textbf{A}\vec{x}=\begin{bmatrix}
2\cdot 1 +  7\cdot2 +3\cdot3 \\
3\cdot 1 +  1\cdot2 +0\cdot3
  \end{bmatrix}=
  \begin{bmatrix}
25 \\
5
  \end{bmatrix}
\end{align}

Y ahora podemos comprobar esto en Python: primero podemos mostrar que la multiplicación de nuestras variables `arreglo` y `arreglo_2D` es posible ya que las columnas del vector 2D corresponden al número de elementos en el arreglo original.

In [15]:
print(arreglo_2D*arreglo)

[[ 1  4  9]
 [ 4 10 18]]




---
<a name='ej-1'></a>
#### **<font color="DodgerBlue">Ejercicio 4 - Operación Matriz vector </font>**

<font color="DarkBlue"> Compruebe usando Python y NumPy que las operaciones de la celda de texto anterior donde se definieron $\textbf{A}$, $\vec{x}$ y $\vec{y}$ son correctas. Para esto genere las variables nuevas necesarias y  realice la operación para obtener $\vec{y}$ e imprima el resultado.

```python
# Arreglo
A = ...
x = ...
operacion = ...
# print tamaño
print()
```

---

También podemos hacer una suma de matrices, que es mientras tengan la misma forma, es decir, que sus dimensiones sean iguales $m \times n$, entonces podemos operarlars. Veamos un ejemplo:

In [16]:
# Ejemplo: Suma de matrices
matriz_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Realizamos la suma de las matrices
resultado_suma = matriz_a + matriz_b

# Imprimimos el resultado
print("Matriz A:")
print(matriz_a)

print("\nMatriz B:")
print(matriz_b)

print("\nResultado de la suma:")
print(resultado_suma)
print("\n---")


Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Resultado de la suma:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

---


Otra operación muy importante es el producto punto $\mathbf{\vec{a}}\cdot\mathbf{\vec{b}}$, que se define para dos vectores de misma longitud como:

\begin{align}
\mathbf{\vec{a}}\cdot\mathbf{\vec{b}} = \sum_{i=0}^N a_ib_i
\end{align}

El producto punto entre dos arreglos se realiza mediante la función `numpy.dot()` o el operador `@`. En el caso de operaciones *vector-matriz*, NumPy facilita la multiplicación de matrices mediante `numpy.matmul()` o simplemente el operador `@`. Estas operaciones ofrecen una forma rápida y optimizada de realizar cálculos lineales y algebraicos en grandes conjuntos de datos, lo que contribuye a la eficiencia y legibilidad del código en entornos científicos y de análisis de datos.


In [17]:
# Ejemplo: Producto punto de vectores
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Calculamos el producto punto de los vectores
resultado_producto_punto = np.dot(vector_a, vector_b)

# Imprimimos el resultado
print("Vector A:", vector_a)
print("Vector B:", vector_b)
print("Resultado del producto punto:", resultado_producto_punto)
print("\n---")

Vector A: [1 2 3]
Vector B: [4 5 6]
Resultado del producto punto: 32

---


En NumPy, las funciones `np.linspace` y `np.arange` son herramientas esenciales para la generación de secuencias de números, pero difieren en su enfoque y aplicación. `np.linspace` se utiliza para crear un array de números espaciados uniformemente en un rango dado, especificando el número total de elementos deseados, mientras que `np.arange` genera una secuencia con un paso específico entre los valores dentro de un rango. La principal diferencia radica en la inclusión o exclusión del valor final del rango: `np.linspace` incluye el valor final, mientras que `np.arange` lo excluye.

A continuación, se presenta un ejemplo de ambas funciones:

In [18]:
# Ejemplo de np.linspace: Generar 5 puntos entre 0 y 1 (inclusivo)
linspace_resultado = np.linspace(0, 1, 5)
print("np.linspace:", linspace_resultado)

# Ejemplo de np.arange: Generar valores del 0 al 1 con paso de 0.25 (exclusivo)
arange_resultado = np.arange(0, 1, 0.25)
print("np.arange:", arange_resultado)

np.linspace: [0.   0.25 0.5  0.75 1.  ]
np.arange: [0.   0.25 0.5  0.75]


In [19]:
array_linspace=np.linspace(0,10,100)
array_arange=np.arange(0,100,10)
print(array_linspace)
print(array_arange)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

NumPy incluye una variedad de funciones que facilitan el análisis de datos en arreglos. Algunas de estas funciones son np.mean para calcular el promedio, `np.min` para encontrar el valor mínimo, `np.max` para obtener el valor máximo, y `np.sum` para sumar todos los elementos. Estas funciones pueden aplicarse a lo largo de un eje específico utilizando el parámetro axis. A continuación, se presenta un ejemplo:

In [20]:
# Recordemos como se ve nuestro arreglo de 2D
print(arreglo_2D)

# Calculamos el promedio de nuestro arreglo de 2D
print(np.mean(arreglo_2D))

# Calculamos el promedio de nuestro arreglo de 2D pero solo en la dimension 0, 
#o sea para cada columna, calculamos el promedio de todas las filas en esa columna
print(np.mean(arreglo_2D,axis=0))

# Tambien podemos obtener el minimo de todo el arreglo en un 1 solo valor
print(np.min(arreglo_2D))

[[1 2 3]
 [4 5 6]]
3.5
[2.5 3.5 4.5]
1


---
<a name='ej-1'></a>
#### **<font color="DodgerBlue">Ejercicio 5 - Calculos de Numpy </font>**

<font color="DarkBlue"> Considerando el arreglo 2D visto anteriormente, calcule lo siguiente:

1. Suma de todo el arreglo
2. Suma por columna
3. Suma por fila
4. Evalúe cual de todos estos valores obtenidos es el valor máximo.



---

---
<a name='ej-1'></a>
#### **<font color="DodgerBlue">Ejercicio 6 - Los números perfectos </font>**

<font color="DarkBlue"> Los números perfectos son aquellos que son iguales a la suma de sus divisores propios (todos sus
divisores a excepción del número en cuestión). 
    
<font color="OrangeRed"> 1. Cree un arreglo de numpy con 5 números aleatorios.
    
<font color="OrangeRed"> 2. Evalúe cada número para ver si es perfecto. Si lo es, imprimalo en pantalla. Si no, imprima "este número como el profe, no es perfecto."


---

### Funciones trigonométricas

NumPy proporciona un conjunto completo de funciones matemáticas, incluyendo funciones trigonométricas y funciones básicas, que son esenciales en diversas disciplinas científicas y de ingeniería. Las funciones trigonométricas, como seno, coseno y tangente, se utilizan comúnmente en geometría, física y procesamiento de señales. NumPy proporciona versiones vectorizadas de estas funciones, permitiendo su aplicación eficiente a arreglos completos de datos. Por ejemplo:


$f(x)=cos(x)$ -> ```np.cos()```

$f(x)=sen(x)$ -> ```np.sin()```

$f(x)=e^{x}$ -> ```np.exp()```

$f(x)=log(x)$ -> ```np.log()``` (logaritmo natural)

In [21]:
x=np.arange(-np.pi,np.pi,0.02)
print(np.cos(x)[0:10])
print(np.exp(x)[0:10])

[-1.         -0.99980001 -0.99920011 -0.99820054 -0.99680171 -0.99500417
 -0.99280864 -0.990216   -0.98722728 -0.98384369]
[0.04321392 0.0440869  0.04497751 0.04588612 0.04681308 0.04775877
 0.04872356 0.04970784 0.050712   0.05173645]


Pero todo esto ¿cómo rayos lo vemos? 