

<div style="display: flex; align-items: ;">

   
# <font color="red">1.8 **NumPy** </font>

<img src="numpy.jpg" width="150" style="margin-right: 0px;">
</div>

NumPy (*Numerical Python*) es una librería de código abierto cuyo objetivo es permitir la computación numérica en Python (<https://numpy.org/>). Al ser una librería, `NumPy` almacena una colección de funciones, módulos o rutinas predefinidas que permiten trabajar con:

- Arreglos multidimensionales (vectores, matrices, cubos de datos).  
- Funciones matemáticas de manera eficiente.  
- Operaciones rápidas sobre grandes volúmenes de datos.  

El principal beneficio de `NumPy` es que permite una generación y manejo de datos extremadamente rápido. `NumPy` tiene su propia estructura de datos incorporada llamado arreglo que es similar a la lista normal de Python, pero puede almacenar y operar con datos de manera mucho más eficiente.

-----

**¿Cómo llamar la librería de NumPy?**

El estándar de la comunidad es importar NumPy como `np`:

```python
import numpy as np

In [1]:
#Vamos a importar NumPy
import numpy as np

## <font color="brown">¿Qué es un arreglo?

Un arreglo es una estructura de datos que **permite almacenar múltiples elementos relacionados bajo un mismo nombre**. Un arreglo de `NumPy` es una estructura optimizada para matemáticas, por lo que se trabaja con números. Cada elemento dentro del arreglo tiene una posición única identificada por un índice, que generalmente comienza desde 0. *Hay dos tipos diferentes de arreglos de *NumPy*: vectores y matrices*.

* **Vectores**: Los vectores son **arreglos de *NumPy* unidimensionales (1D)**, es decir, similar a las listas simples de elementos, como `[1, 2, 3, 4]`.

* **Matrices**: Las matrices son **arreglos bidimensionales (2D)** con filas y columnas, útiles para representar tablas de datos.

También pueden expandir los arreglos de *NumPy* a diferentes niveles de profundidad, es decir, trabajar con matrices de tres, cuatro, cinco, seis o más dimensiones.

<img src="arrays.png" width="700" style="margin-left: 150px;">


### Arreglos en NumPy
* **`np.array()`**: Es la función de NumPy que permite **crear un arreglo** a partir de una lista o lista de listas de Python.  
Al usarla, obtenemos un objeto de tipo `np.ndarray`.  

* `np.ndarray`: es la **clase fundamental de NumPy**, la que define a los arreglos de **N dimensiones**. Cada arreglo de NumPy (ya sea vector, matriz o cubo de datos) es en realidad un objeto `ndarray`.
Además, todos los elementos de un arreglo son del **mismo tipo**, lo que hace posible operaciones rápidas y vectorizadas.



La mayoría de los arreglos NumPy **tienen algunas restricciones**. Por ejemplo:

- Todos los elementos del array deben ser del mismo tipo de datos.
- Una vez creado, el tamaño total del array no puede cambiar.
- Cada fila de un array bidimensional debe tener el mismo número de columnas.

  
-------

### <font color="brown"> **Vectores (1D)**

In [4]:
#Ahora vamos a crear un arreglo, para ello usamos la función np.array()
arreglo=np.array([1,2,3]) #Arreglo unidimensional
print(arreglo)

[1 2 3]


In [5]:
#Checando el tipo de objeto
print(type(arreglo))

<class 'numpy.ndarray'>


### <font color="darkblue"> Listas vs Arreglos

##### **Si un arreglo unidimensional está conformado por una lista ¿Por que no sólo uso listas en vez de arreglos?¿Cuál es la diferencia?**

A diferencia de una lista de Python, un *arreglo de NumPy* (`ndarray`) está optimizado para almacenar datos numéricos y realizar operaciones de manera vectorizada (sin ciclos explícitos).

#### <font color="orange"> Ejemplo: Operando listas

In [5]:
#Vamos a definir una lista 
lista=[1,2,3,4,5,6]

In [6]:
#Si quiero multiplicar cada número de la lista por 2, ¿Cómo lo haría?
for i in lista:
    print(i*2)

#¿ Y si quiero guardar los resultados de las operaciones?

2
4
6
8
10
12


In [7]:
#Para guardar las operaciones tendríamos que crear una nueva lista e ir agregando el resultado en cada iteración
lista_resultados=[]
for i in lista:
    lista_resultados.append(i*2)
print(lista_resultados)

[2, 4, 6, 8, 10, 12]


#### <font color="orange"> Ejemplo: Operando arreglos

In [8]:
#Vamos a definir un arreglo con la misma lista
arreglo_2=np.array([1,2,3,4,5,6])      # ò arreglo_2=np.array(lista)

In [9]:
#Si quiero multiplicar cada número del arreglo por 2, ¿Cómo le hacemos? con arreglos todo es más sencillo
arreglo_2*2

array([ 2,  4,  6,  8, 10, 12])

In [10]:
#Si quiero guardar dicha operación basta con asignarle una variable

arreglo2_mul=arreglo_2*2
arreglo2_mul

array([ 2,  4,  6,  8, 10, 12])

In [11]:
lista

[1, 2, 3, 4, 5, 6]

In [12]:
#¿Qué pasa si intento hacer la misma operación con las listas?
lista*2 #Me duplica los mismos elementos

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

##### <font color="darkblue"> **Como pudieron observar, los arreglos no necesitan de ciclos para operar datos. Además, con los arreglos pueden usar todos los operadores matemáticos (`+`,`*`,`/`,`%`, etc.). La siguiente tabla resume las diferencias entre listas y arreglos de *NumPy*.** 
|Lista|Arreglo NumPy|
|-------|-------------|
|General|	Científico|
|Puede mezclar tipos|Tipo homogéneo|
|Lenta para cálculos|Muy rápida|
|No vectorizada|Vectorizada|
|No tiene forma (shape)|Tiene dimensión y forma|

-----

**Hasta ahora hemos creado arreglos, los cuales definimos nosotros; pero qué pasaría si me dan un arreglo cualquiera y quiero conocer algunas de sus características como si el arreglo es de 1D, 2D, 3D, etc; o la cantidad de valores en cada dimensión; o el total de valores del arreglo. Para ello, ocupamos los atributos de los arreglos.**

## Atributos en Python

Así como una persona cuenta con características específicas como edad, estatura o nombre; los objetos en Python (como los arreglos de NumPy) también tienen características propias. A estas se les conoce como **atributos**.  

Un *array* es como una tabla de Excel, por lo que sus atributos son:  

- `.ndim`: Número de dimensiones.
- `.shape`: Tupla de enteros positivos que especifican el número de elementos a lo largo de cada dimensión.  
- `.size`: El número fijo y total de elementos en el array. 
- `.dtype`: Tipo de dato. 


En **JupyterHub**, puedes explorar los atributos de un objeto escribiendo su nombre y luego dos veces la tecla `TAB`.  Esto muestra la lista de métodos y atributos disponibles.

In [6]:
#Creemos un arreglo de 1D y mostremos sus atributos
arreglo_4=np.array([2,4,6,8])

In [7]:
arreglo_4

array([2, 4, 6, 8])

In [8]:
print("Arreglo:\n", arreglo_4)
print("Número de dimensiones (ndim):", arreglo_4.ndim)
print("Forma (shape):", arreglo_4.shape)
print("Número de elementos (size):", arreglo_4.size)
print("Tipo de datos (dtype):", arreglo_4.dtype)

Arreglo:
 [2 4 6 8]
Número de dimensiones (ndim): 1
Forma (shape): (4,)
Número de elementos (size): 4
Tipo de datos (dtype): int64



## <font color="darkblue">¿Cómo selecciono elementos?

### **Slicing**

Para seleccionar elementos de un arreglo de NumPy (*slicing*), se utiliza la **notación de corchetes** `[]`.  Recuerda que *Python usa indexación basada en cero*, es decir, el primer elemento de un arreglo tiene índice `0`.


#### Sintaxis general

`[inicio : fin : paso]`

- **inicio** → índice donde comienza el corte (incluido).  
- **fin** → índice donde termina el corte (excluido).  
- **paso** → cada cuántos elementos se toma uno (opcional).  



#### <font color="orange"> Ejemplo: Slicing en 1D

In [9]:
#Ejemplo de slicing
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [10]:
print(arr[0])      # primer elemento

1


In [11]:
print(arr[1:4])    # del índice 1 al 3

[2 3 4]


In [12]:
print(arr[::2])    # de inicio a fin, cada 2 

[1 3 5 7 9]


In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Los elementos de los arreglos son mutables
arr[4]=11  #Quiero cambiar el elemento con el índice 4 por el número 11

In [15]:
arr

array([ 1,  2,  3,  4, 11,  6,  7,  8,  9, 10])

----

### <font color="brown"> **Matrices (2D o más)**

La verdadera potencia de NumPy se aprecia al usar **arreglos de dos o más dimensiones**.

- Un **arreglo 2D** se puede pensar como una **tabla o matriz**: filas × columnas. Ejemplo: datos meteorológicos de varias estaciones a lo largo de varios días.
  Una manera de visualizarlo quizás más común a lo que estamos acostumbrados es:

$A=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
  \end{bmatrix}
$

- Un **arreglo nD** extiende la idea a tres o más dimensiones:  
  - 3D: una pila de matrices (ejemplo: Tiempo x Latitud x Longitud).  
  - 4D o más: series temporales de datos espaciales y multivariados (ejemplo: Tiempo × Nivel vertical/Profundidad × Latitud × Longitud).  


#### Relevancia en Ciencias de la Tierra
Los arreglos multidimensionales son esenciales porque los datos que usamos rara vez son listas simples.  
Al contrario, suelen organizarse en **estructuras espaciales y temporales**:

- Tablas con estaciones y variables meteorológicas.  
- Mapas 2D de precipitación, temperatura o calidad del aire.  
- Cubos 3D o 4D que integran espacio (latitud, longitud, altura) y tiempo.  

*NumPy* nos permite **almacenar, manipular y analizar** todos estos datos de manera eficiente.


### <font color="orange"> Ejemplo 1: Arreglo 2D
Los arreglo bidimensionales son creadas pasando una lista de lista dentro del método `np.array()`

In [16]:
#Creamos un arreglo 2D
arreglo_2D=np.array([[1,2,3],[5,6,7]])

# imprimimos el arreglo
print('Arreglo 2D')
arreglo_2D

Arreglo 2D


array([[1, 2, 3],
       [5, 6, 7]])

In [19]:
#Imprimamos sus atributos
print(arreglo_2D.shape)
print(arreglo_2D.size)
print(arreglo_2D.ndim)
print(arreglo_2D.dtype)

(2, 3)
6
2
int64


### <font color="orange"> Ejemplo 2: Arreglo 3D

In [20]:
arreglo_3D=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #Misma cantidad de filas y columnas
arreglo_3D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
#Atributos
arreglo_3D.shape
arreglo_3D.size

9

In [22]:
#Ejemplo con más de una capa

arreglo_3D_2capas = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

In [23]:
arreglo_3D_2capas

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arreglo_3D_2capas.shape

(2, 2, 3)

---

**<font color="darkblue">Anteriormente vimos cómo podemos acceder a los valores de un array de 1D. Pero, ¿Y si el arreglo tiene más de una dimensión?**



#### <font color="orange"> Ejemplo: Slicing 2D

In [25]:
# Arreglo bidimensional (matriz)
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #¿Cuántas filas y columnas tiene este arreglo?

print('Matriz')
print(matriz)

Matriz
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# Seleccionar la primera fila (índice 0)
primera_fila = matriz[0, :]  #Primero se indica la fila y luego la columna
print(primera_fila)

[1 2 3]


In [27]:
# Seleccionar la segunda columna (índice 1)
segunda_columna = matriz[:, 1]
segunda_columna

array([2, 5, 8])

In [28]:
# Seleccionar un subconjunto de la matriz
submatriz = matriz[1:3, 0:2]
submatriz

array([[4, 5],
       [7, 8]])

#### <font color="orange"> Ejemplo: Slicing 3D

In [29]:
#Retomamos el arreglo 3D que hicimos previamente
arreglo_3D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [30]:
#Segunda columna
arreglo_3D[:,:,1]  #profundidad/capas, filas, columnas

array([[2, 5, 8]])

In [31]:
#Tercera fila
arreglo_3D[:,2,:]

array([[7, 8, 9]])

In [32]:
#Submatriz
arreglo_3D[:,:2,1:3] #¿Qué me selecciona?

array([[[2, 3],
        [5, 6]]])

---

## <font color="purple"> Ejercicio 1

- Genere un arreglo de numpy de 3 dimensiones de la forma (1,3,2) e imprime sus atributos.
- Luego obtenga a través de un slice, o una submatriz, el elemento que se encuentra en la segunda fila primer columna.


In [37]:
#Creando arreglo
arreglo_3D_example=np.array([[[9,11],[26,7],[24,-2]]])

#Imprimiendo atributos
print("Arreglo:\n", arreglo_3D_example)
print("Número de dimensiones (ndim):", arreglo_3D_example.ndim)
print("Forma (shape):", arreglo_3D_example.shape)
print("Número de elementos (size):", arreglo_3D_example.size)
print("Tipo de datos (dtype):", arreglo_3D_example.dtype)

Arreglo:
 [[[ 9 11]
  [26  7]
  [24 -2]]]
Número de dimensiones (ndim): 3
Forma (shape): (1, 3, 2)
Número de elementos (size): 6
Tipo de datos (dtype): int64


In [40]:
#Elemento de la segunda fila, primer columna, este es el elemento 26
arreglo_3D_example[:,1,0]

array([26])

-----

### **Métodos Incorporados**
Un método en NumPy es una función que pertenece a un arreglo (ndarray). Los arreglos de NumPy vienen con un número de métodos incorporados útiles:

- `np.zeros()`: Crea un array lleno de ceros (0)
- `np.ones()`: Crea un array lleno de unos (1)
- `np.empty()`: Crea una matriz vacía
- `np.full()`: Crea una matriz y la llena del valor determinado.
- `np.arange()`: Crea un array con una secuencia de elementos.
- `np.linspace()`: Crea un array dividiendo un rango de números en intervalos.

In [41]:
# Ejemplos
arr2 = np.zeros(5)
arr3 = np.ones((2,3))   # matriz 2x3 de unos
arr4 = np.full((2,2), 7) # matriz llena con 7
arr5 = np.arange(0, 10, 2)  # de 0 a 9 en pasos de 2
arr6 = np.linspace(0, 1, 5) # 5 valores entre 0 y 1

In [46]:
#Vamos a comparar los que nos imprime linspace y arange usando el mismo rango
print(np.linspace(0,20,5))
print(np.arange(0, 20, 5))

[ 0.  5. 10. 15. 20.]
[ 0  5 10 15]


#### `linspace` vs `arange`

*Idea clave:* ambos generan secuencias numéricas, pero con enfoques distintos.

- **`np.linspace(inicio, fin, num)`**  
  Eliges **cuántos puntos** quieres. Por defecto son 50 e **incluye** el `fin`.
  - Útil para mallas uniformes con un número exacto de muestras (tiempo, profundidad, longitudes).
  - Evita errores de redondeo en pasos decimales.


- **`np.arange(inicio, fin, paso)`**  
  Eliges el **tamaño del paso**. El arreglo es semiabierto: incluye `inicio`, **excluye** `fin`.
  - Ideal con pasos enteros (índices, días, conteos).
  - Con pasos decimales puede acumular errores de punto flotante.


In [47]:
# inicio,fin = 0,5
con_linespace=np.linspace(0,5)
print(con_linespace)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [48]:
# inicio,fin=0,5
con_arange=np.arange(0,5)
print(con_arange)


[0 1 2 3 4]


## **Números aleatorios con NumPy**

Con NumPy podemos crear números aleatorios usando el módulo `np.random`

In [49]:
#Ejemplo
#Primero plantamos nuestra semilla, que nos ayudará a siempre tener los mismos números.
np.random.seed(0) 

In [50]:
# Un número aleatorio
x = np.random.rand()
print("x =", x)

# Un vector de 5 aleatorios
v = np.random.rand(5)
print("v =", v)

# Una matriz 2x3 de aleatorios
M = np.random.rand(2, 3)
print("M =\n", M)


x = 0.5488135039273248
v = [0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]
M =
 [[0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]


In [51]:
np.random.seed(0) 
x = np.random.rand()
print("x =", x)

x = 0.5488135039273248


In [52]:
#np.random.seed(0) 
# Un vector de 5 aleatorios
v = np.random.rand(5)
print("v =", v)


v = [0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]


In [53]:
# Una matriz 2x3 de aleatorios
M = np.random.rand(2, 3)
print("M =\n", M)

M =
 [[0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]


#### ¿Cómo genero valores random dentro de un rango? 

In [54]:
# Un entero entre 0 y 9 (10 no incluido)
n = np.random.randint(0, 10)
print("n =", n)

n = 8


In [55]:
# 3 enteros entre 0 y 9 (10 no incluido)
n = np.random.randint(0, 10,3)
print("n =", n)

n = [1 5 9]


In [56]:
a = np.random.uniform(1, 10,5)
a

array([1.63932452, 1.7841637 , 1.18196558, 8.49357861, 8.00341076])

-----

### <font color="purple"> Ejercicio 2
Generen un arreglo de numpy con 5 elementos aleatorios, o usando `np.arange` o `np.linspace`  y compruebe que su tamaño es de 5 elementos y que su forma es de (5,).

In [65]:
np.random.seed(56) #Para que siempre salga el mismo valor aleatorio

elemento_5=np.random.uniform(1,50,5) #Generando mis cinco elementos aleatorios

print(elemento_5)

#Corroborando la forma
elemento_5.shape

[49.22540068 17.33720103 34.01137961 10.62313044 18.36787677]


(5,)

--------

### Operaciones básicas con arreglos

Una de las grandes ventajas de **NumPy** es que permite realizar operaciones directamente sobre arreglos completos, sin necesidad de escribir bucles.  
A esto se le llama **vectorización**: aplicar una operación a todos los elementos de un arreglo de manera automática y eficiente.

#### Operaciones elemento a elemento

- `+` → suma  
- `-` → resta  
- `*` → multiplicación  
- `/` → división  
- `**` → potencia

In [66]:
#Ejemplo
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)   
print(a * b) 

print(a ** 2) 

[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]


In [75]:
#Ejemplo 2
matriz_dosd=np.array([[1,2,3],[5,6,7]])
matriz_dosd1=np.array([[8,9,13],[15,16,17]])

In [76]:
matriz_dosd

array([[1, 2, 3],
       [5, 6, 7]])

In [77]:
matriz_dosd1

array([[ 8,  9, 13],
       [15, 16, 17]])

In [78]:
#Realizando la suma
print(matriz_dosd+matriz_dosd1)

[[ 9 11 16]
 [20 22 24]]


In [79]:
#¿Qué pasa con las matrices de tres dimensiones?
matriz_tresd=np.array([[[1,2,3],[5,6,7]],[[8,9,13],[15,16,17]]])
matriz_tres1=np.array([[[1,2,3],[5,6,7]],[[8,9,13],[15,16,17]]])
matriz_tres1.shape

(2, 2, 3)

In [80]:
matriz_tresd

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 8,  9, 13],
        [15, 16, 17]]])

In [81]:
matriz_tres1

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 8,  9, 13],
        [15, 16, 17]]])

In [82]:
print(matriz_tresd+matriz_tres1)

[[[ 2  4  6]
  [10 12 14]]

 [[16 18 26]
  [30 32 34]]]


### Operaciones prefabricadas en NumPy

Además de las operaciones aritméticas básicas, **NumPy** incluye muchas funciones ya “prefabricadas” para calcular propiedades de los datos de manera rápida y eficiente.  
Estas funciones actúan directamente sobre los arreglos, sin necesidad de escribir ciclos.

 1. `np.mean()` calcula el valor medio de todos los elementos del arreglo.
 2. `np.sum ()` Suma todos los elementos del arreglo.
 3. `np.max ()` Encuentra el valor máximo del arreglo.
 4. `np.min ()` Encuentra el valor mínimo del arreglo.


In [83]:
#Encontremos el promedio, la suma, el valor máximo y mínimo del siguiente arreglo.
x=np.array([2,8,9,1,100,5])

In [85]:
print("Suma de x",np.sum(x))
print("Promedio de x",np.mean(x))
print("Valor máximo de x",np.max(x))
print("Valor mínimo de z",np.min(x))

Suma de x 125
Promedio de x 20.833333333333332
Valor máximo de x 100
Valor mínimo de z 1


---

### <font color="purple"> Ejercicio 3

Crea un código que pueda ser reutilizado, en donde se generen aleatoriamente concentraciones horarias de material particulado PM2.5 (µg/m³) entre 0 y 80 (µg/m³). Además, debe calcular el valor promedio, máximo y mínimo registrado durante el día.

In [87]:
def concentraciones():
    concen=np.random.uniform(0,81,24) #El valor final no lo incluye, pedimos 24 valores porque son horarios durante un día
    print("Promedio",np.mean(concen))
    print("Valor máximo",np.max(concen))
    print("Valor mínimo",np.min(concen))

In [90]:
#Llamando la función
concentraciones()

Promedio 45.63055775343948
Valor máximo 80.68488807613004
Valor mínimo 6.0814670406199465


### Operaciones por *axis* en NumPy

Las funciones de NumPy, como `np.mean`, `np.sum` o `np.max`, pueden aplicarse a todo el arreglo **o a lo largo de un eje específico**.  
Ese eje se indica con el argumento `axis`.

#### ¿Qué significa `axis`?
- En un **arreglo 2D** (matriz):
  - `axis=0` → opera **a lo largo de las filas**, es decir, combina los valores **columna por columna**.  
  - `axis=1` → opera **a lo largo de las columnas**, es decir, combina los valores **fila por fila**.  

En otras palabras:  
- `axis=0` → reduce el arreglo verticalmente.  
- `axis=1` → reduce el arreglo horizontalmente.  

---

In [91]:
mat = np.array([[1, 2, 3],
                [-4, 5, 6],
                [7, 8, -9]])
print("Matriz:\n", mat)

Matriz:
 [[ 1  2  3]
 [-4  5  6]
 [ 7  8 -9]]


In [92]:
# Promedio de cada columna (axis=0)
print("Promedio por columna:", np.mean(mat, axis=0))

# Promedio de cada fila (axis=1)
print("Promedio por fila:", np.mean(mat, axis=1))

# Máximo por columna
print("Máximos por columna:", np.max(mat, axis=0))

# Suma de cada fila
print("Suma por fila:", np.sum(mat, axis=1))

Promedio por columna: [1.33333333 5.         0.        ]
Promedio por fila: [2.         2.33333333 2.        ]
Máximos por columna: [7 8 6]
Suma por fila: [6 7 6]


In [91]:
# Promedio de cada columna (axis=0)
print("Promedio por columna:", np.mean(mat, axis=0))

Promedio por columna: [1.33333333 5.         0.        ]


In [92]:
# Promedio de cada fila (axis=1)
print("Promedio por fila:", np.mean(mat, axis=1))


Promedio por fila: [2.         2.33333333 2.        ]


In [93]:
# Máximo por columna
print("Máximos por columna:", np.max(mat, axis=0))

Máximos por columna: [7 8 6]


In [94]:
print("Suma por fila:", np.sum(mat, axis=2))

Suma por fila: [6 7 6]


#### ¿ Y con arreglos 3D?

In [4]:
matriz_tres1=np.array([[[1,2,3],[5,6,7]],[[8,9,13],[15,16,17]]])
matriz_tres1

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 8,  9, 13],
        [15, 16, 17]]])

<font color="brown"> **En el caso de los arreglos 3D, el operar por axis cambia un poco. axis puede tomar tres valores diferentes: 0 (capas), 1 (columnas) y 2 (filas)**

<font color="brown">

In [5]:
#Sumando por axis=0, es decir, nos sumará por capas
print("Suma por capas (3D):",np.sum(matriz_tres1,axis=0))
print(np.sum(matriz_tres1,axis=0).shape) #Debido a que tenemos una sola capa, al sumar por axis, nos reduce la dimensión del arreglo

Suma por capas (3D): [[ 9 11 16]
 [20 22 24]]
(2, 3)


In [6]:
#Sumando por axis=1, es decir, nos sumará por columnas dentro de cada capa. Es decir, nos suma las columnas de la primera capa y luego la de la segunda
print("Suma por columnas (3D):",np.sum(matriz_tres1,axis=1))
print(np.sum(matriz_tres1,axis=1).shape)

Suma por columnas (3D): [[ 6  8 10]
 [23 25 30]]
(2, 3)


In [8]:
#Sumando por axis=2, es decir, nos sumará por filas dentro de cada capa. Es decir, nos suma las filas dentro de la primera capa y luego la de la segunda
print("Suma por filas (3D):",np.sum(matriz_tres1,axis=2))
print(np.sum(matriz_tres1,axis=2).shape) #Acá reducimos la dimensión pero también la cantidad de columnas

Suma por filas (3D): [[ 6 18]
 [30 48]]
(2, 2)


### <font color="purple"> Ejercicio 4
Crea un arreglo 2D y un arreglo 3D, calcula lo siguiente:

1. Suma de todo el arreglo
2. Suma por columna
3. Suma por fila
4. Evalúe cual de todos estos valores obtenidos es el más grande, o el valor máximo.


In [19]:
#Creando arreglo 2D
arreglo_2_example=np.array([[3,67,-10],[21,4,5]])
print(arreglo_2_example)
print(arreglo_2_example.shape)

#Resolviendo los puntos
print("Suma de todo el arreglo",np.sum(arreglo_2_example))
print("Suma por columna",np.sum(arreglo_2_example,axis=0))
print("Suma por fila", np.sum(arreglo_2_example,axis=1))
print("Valor máximo",np.max(arreglo_2_example))

[[  3  67 -10]
 [ 21   4   5]]
(2, 3)
Suma de todo el arreglo 90
Suma por columna [24 71 -5]
Suma por fila [60 30]
Valor máximo 67


In [3]:
#Creando arreglo 3D
arreglo_3_example=np.array([[[3,67,-10],[21,4,5],[327,3473,48]]])
print(arreglo_3_example)
print(arreglo_3_example.shape)

#Resolviendo los puntos
print("Suma de todo el arreglo",np.sum(arreglo_3_example))
print("Suma por columna",np.sum(arreglo_3_example,axis=1))
print("Suma por fila", np.sum(arreglo_3_example,axis=2))
print("Valor máximo",np.max(arreglo_3_example))

[[[   3   67  -10]
  [  21    4    5]
  [ 327 3473   48]]]
(1, 3, 3)
Suma de todo el arreglo 3938
Suma por columna [[ 351 3544   43]]
Suma por fila [[  60   30 3848]]
Valor máximo 3473


### Funciones trigonométricas

NumPy proporciona un conjunto completo de funciones matemáticas, incluyendo funciones trigonométricas y funciones básicas, que son esenciales en diversas disciplinas científicas y de ingeniería. Las funciones trigonométricas, como seno, coseno y tangente, se utilizan comúnmente en geometría, física y procesamiento de señales. NumPy proporciona versiones vectorizadas de estas funciones, permitiendo su aplicación eficiente a arreglos completos de datos. Por ejemplo:


$f(x)=cos(x)$ -> ```np.cos()```

$f(x)=sen(x)$ -> ```np.sin()```

$f(x)=e^{x}$ -> ```np.exp()```

$f(x)=log(x)$ -> ```np.log()``` (logaritmo natural)

In [9]:
import numpy as np
#Crea valores a evaluar
x=np.arange(-np.pi,np.pi,0.02)

print(np.cos(x)[0:10])
print(np.exp(x)[0:10])

[-1.         -0.99980001 -0.99920011 -0.99820054 -0.99680171 -0.99500417
 -0.99280864 -0.990216   -0.98722728 -0.98384369]
[0.04321392 0.0440869  0.04497751 0.04588612 0.04681308 0.04775877
 0.04872356 0.04970784 0.050712   0.05173645]


#### **Pero todo esto ¿Cómo lo vemos?**